-- Insert sample products for MD Electronics
WITH category_ids AS (
  SELECT id, slug FROM categories
),
brand_ids AS (
  SELECT id, slug FROM brands
)
INSERT INTO products (
  id, name, slug, description, short_description, price, original_price, 
  stock_quantity, sku, images, specifications, warranty_info, 
  is_active, is_featured, category_id, brand_id, created_at, updated_at
) VALUES
-- Refrigerators
(uuid_generate_v4(), 'Samsung French Door Refrigerator 28 cu ft', 'samsung-french-door-28', 
 'Experience the ultimate in food preservation with this spacious French door refrigerator featuring Twin Cooling Plus technology, FlexZone drawer, and Energy Star certification.', 
 'Spacious French door refrigerator with advanced cooling technology', 
 1299.99, 1599.99, 15, 'REF-SAM-001',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"capacity": "28 cu ft", "type": "French Door", "energy_rating": "Energy Star", "features": ["Twin Cooling Plus", "FlexZone Drawer", "LED Lighting", "Ice Maker"]}',
 '2 years manufacturer warranty',
 true, true, 
 (SELECT id FROM category_ids WHERE slug = 'refrigerators'),
 (SELECT id FROM brand_ids WHERE slug = 'samsung'),
 now(), now()),

(uuid_generate_v4(), 'LG Side-by-Side Refrigerator 26 cu ft', 'lg-side-by-side-26',
 'Modern side-by-side refrigerator with InstaView Door-in-Door technology, smart connectivity, and efficient linear compressor for optimal performance.',
 'Smart side-by-side refrigerator with InstaView technology',
 1199.99, 1399.99, 12, 'REF-LG-002',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"capacity": "26 cu ft", "type": "Side-by-Side", "energy_rating": "Energy Star", "features": ["InstaView Door-in-Door", "Smart ThinQ", "Linear Compressor", "Water Dispenser"]}',
 '2 years manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'refrigerators'),
 (SELECT id FROM brand_ids WHERE slug = 'lg'),
 now(), now()),

(uuid_generate_v4(), 'Whirlpool Top Freezer Refrigerator 18 cu ft', 'whirlpool-top-freezer-18',
 'Classic top freezer design with reliable performance',
 'Affordable and reliable top freezer refrigerator',
 699.99, 799.99, 20, 'WHP-REF-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"capacity": "18 cu ft", "energy_star": true}',
 '1 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'refrigerators'),
 (SELECT id FROM brand_ids WHERE slug = 'whirlpool'),
 now(), now()),

(uuid_generate_v4(), 'GE Bottom Freezer Refrigerator 24 cu ft', 'ge-bottom-freezer-24',
 'Bottom freezer refrigerator with easy access fresh food compartment',
 'Convenient bottom freezer design',
 999.99, 1199.99, 8, 'GE-REF-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"capacity": "24 cu ft", "energy_star": true}',
 '2 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'refrigerators'),
 (SELECT id FROM brand_ids WHERE slug = 'ge'),
 now(), now()),

-- Ovens
(uuid_generate_v4(), 'Bosch Built-in Electric Oven 30"', 'bosch-builtin-electric-30',
 'Professional-grade built-in electric oven with European convection, self-cleaning function, and precise temperature control for perfect cooking results.',
 'High-performance built-in oven with advanced features',
 899.99, 1099.99, 10, 'BSH-OVN-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"size": "30 inch", "type": "electric", "convection": true, "self_cleaning": true}',
 '2 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'ovens'),
 (SELECT id FROM brand_ids WHERE slug = 'bosch'),
 now(), now()),

(uuid_generate_v4(), 'KitchenAid Double Wall Oven', 'kitchenaid-double-wall-oven',
 'Double wall oven for serious home chefs',
 'Professional double oven with precision cooking',
 1599.99, 1899.99, 5, 'KA-OVN-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"size": "30 inch", "type": "electric", "convection": true, "double_oven": true}',
 '3 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'ovens'),
 (SELECT id FROM brand_ids WHERE slug = 'kitchenaid'),
 now(), now()),

(uuid_generate_v4(), 'GE Gas Range with Oven', 'ge-gas-range-with-oven',
 'Gas range with spacious oven and precise temperature control',
 'Reliable gas range for everyday cooking',
 749.99, 899.99, 15, 'GE-RNG-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"size": "30 inch", "type": "gas", "burners": 5, "oven_capacity": "5.0 cu ft"}',
 '1 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'ovens'),
 (SELECT id FROM brand_ids WHERE slug = 'ge'),
 now(), now()),

(uuid_generate_v4(), 'Samsung Smart Electric Range', 'samsung-smart-electric-range',
 'Smart electric range with Wi-Fi connectivity and app control',
 'Connected cooking with smart features',
 1199.99, 1399.99, 7, 'SAM-RNG-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"size": "30 inch", "type": "electric", "smart_features": true, "wifi": true}',
 '2 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'ovens'),
 (SELECT id FROM brand_ids WHERE slug = 'samsung'),
 now(), now()),

-- Televisions
(uuid_generate_v4(), 'Samsung 65" QLED 4K Smart TV', 'samsung-65-qled-4k',
 'Immerse yourself in stunning 4K entertainment with Quantum Dot technology, HDR10+ support, and Tizen smart platform with voice control.',
 'Stunning 4K QLED display with smart capabilities',
 1499.99, 1799.99, 12, 'SAM-TV-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"size": "65 inch", "resolution": "4K", "display_type": "QLED", "smart_tv": true, "hdr": true}',
 '1 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'televisions'),
 (SELECT id FROM brand_ids WHERE slug = 'samsung'),
 now(), now()),

(uuid_generate_v4(), 'LG 55" OLED 4K Smart TV', 'lg-55-oled-4k',
 'Experience perfect blacks and infinite contrast with OLED technology, Dolby Vision, and Google TV platform for endless entertainment.',
 'Premium OLED display with exceptional picture quality',
 1299.99, 1599.99, 8, 'LG-TV-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"size": "55 inch", "resolution": "4K", "display_type": "OLED", "smart_tv": true, "hdr": true}',
 '1 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'televisions'),
 (SELECT id FROM brand_ids WHERE slug = 'lg'),
 now(), now()),

(uuid_generate_v4(), 'Sony 75" LED 4K Smart TV', 'sony-75-led-4k',
 'Large screen LED TV with excellent picture processing',
 'Immersive 75-inch 4K experience',
 1799.99, 2199.99, 6, 'SNY-TV-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"size": "75 inch", "resolution": "4K", "display_type": "LED", "smart_tv": true, "hdr": true}',
 '2 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'televisions'),
 (SELECT id FROM brand_ids WHERE slug = 'sony'),
 now(), now()),

(uuid_generate_v4(), 'Samsung 43" Crystal UHD Smart TV', 'samsung-43-crystal-uhd',
 'Affordable 4K smart TV with crystal clear picture',
 'Budget-friendly 4K smart TV',
 399.99, 499.99, 25, 'SAM-TV-002',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"size": "43 inch", "resolution": "4K", "display_type": "LED", "smart_tv": true}',
 '1 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'televisions'),
 (SELECT id FROM brand_ids WHERE slug = 'samsung'),
 now(), now()),

-- Air Conditioners
(uuid_generate_v4(), 'LG 12000 BTU Window AC Unit', 'lg-12000-btu-window-ac',
 'Efficient window air conditioner with dual inverter technology, smart connectivity, and energy-saving features for optimal comfort.',
 'Powerful cooling for rooms up to 550 sq ft',
 299.99, 399.99, 18, 'LG-AC-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"btu": "12000", "type": "window", "room_size": "550 sq ft", "energy_star": true}',
 '2 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'air-conditioners'),
 (SELECT id FROM brand_ids WHERE slug = 'lg'),
 now(), now()),

(uuid_generate_v4(), 'Frigidaire Portable AC 14000 BTU', 'frigidaire-portable-ac-14000',
 'Portable air conditioner with easy installation',
 'Mobile cooling solution with remote control',
 449.99, 549.99, 12, 'FRG-AC-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"btu": "14000", "type": "portable", "room_size": "700 sq ft", "remote_control": true}',
 '1 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'air-conditioners'),
 (SELECT id FROM brand_ids WHERE slug = 'frigidaire'),
 now(), now()),

(uuid_generate_v4(), 'GE Smart Window AC 8000 BTU', 'ge-smart-window-ac-8000',
 'Smart window AC with Wi-Fi connectivity and app control',
 'Connected cooling with smart features',
 349.99, 429.99, 15, 'GE-AC-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"btu": "8000", "type": "window", "room_size": "350 sq ft", "smart_features": true, "wifi": true}',
 '2 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'air-conditioners'),
 (SELECT id FROM brand_ids WHERE slug = 'ge'),
 now(), now()),

(uuid_generate_v4(), 'Samsung Split System AC 18000 BTU', 'samsung-split-system-ac-18000',
 'Ductless split system for efficient whole-room cooling',
 'Professional installation split system',
 899.99, 1199.99, 6, 'SAM-AC-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"btu": "18000", "type": "split_system", "room_size": "900 sq ft", "inverter": true}',
 '3 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'air-conditioners'),
 (SELECT id FROM brand_ids WHERE slug = 'samsung'),
 now(), now()),

-- Washing Machines
(uuid_generate_v4(), 'Whirlpool Top Load Washer 4.3 cu ft', 'whirlpool-top-load-43',
 'Reliable top-load washing machine with Adaptive Wash technology, multiple wash cycles, and energy-efficient operation.',
 'Dependable top load washing machine',
 549.99, 649.99, 20, 'WHP-WSH-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"capacity": "4.3 cu ft", "type": "top_load", "energy_star": true, "wash_cycles": 12}',
 '2 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'washing-machines'),
 (SELECT id FROM brand_ids WHERE slug = 'whirlpool'),
 now(), now()),

(uuid_generate_v4(), 'LG Front Load Washer 4.5 cu ft', 'lg-front-load-45',
 'Advanced front-load washer with TurboWash technology, steam cleaning, and smart connectivity for superior cleaning performance.',
 'Advanced front load washer with steam technology',
 799.99, 999.99, 14, 'LG-WSH-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"capacity": "4.5 cu ft", "type": "front_load", "energy_star": true, "steam": true, "wash_cycles": 14}',
 '2 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'washing-machines'),
 (SELECT id FROM brand_ids WHERE slug = 'lg'),
 now(), now()),

(uuid_generate_v4(), 'Samsung Smart Washer 5.2 cu ft', 'samsung-smart-washer-5-2',
 'Smart washing machine with Wi-Fi connectivity and app control',
 'Connected laundry with smart features',
 999.99, 1199.99, 10, 'SAM-WSH-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"capacity": "5.2 cu ft", "type": "front_load", "smart_features": true, "wifi": true, "steam": true}',
 '3 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'washing-machines'),
 (SELECT id FROM brand_ids WHERE slug = 'samsung'),
 now(), now()),

(uuid_generate_v4(), 'GE Top Load Washer 4.2 cu ft', 'ge-top-load-washer-4-2',
 'Affordable top load washer for everyday use',
 'Budget-friendly washing solution',
 449.99, 549.99, 16, 'GE-WSH-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"capacity": "4.2 cu ft", "type": "top_load", "wash_cycles": 11}',
 '1 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'washing-machines'),
 (SELECT id FROM brand_ids WHERE slug = 'ge'),
 now(), now()),

-- Deep Freezers
(uuid_generate_v4(), 'Haier Chest Freezer 7.1 cu ft', 'haier-chest-freezer-71',
 'Spacious chest freezer with energy-efficient operation, adjustable temperature control, and removable storage baskets.',
 'Spacious chest freezer with energy efficiency',
 299.99, 349.99, 22, 'FRG-FRZ-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"capacity": "7.1 cu ft", "type": "chest", "energy_star": true, "temperature_alarm": true}',
 '1 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'deep-freezers'),
 (SELECT id FROM brand_ids WHERE slug = 'haier'),
 now(), now()),

(uuid_generate_v4(), 'Electrolux Upright Freezer 14 cu ft', 'electrolux-upright-14',
 'Large upright freezer with frost-free operation, LED lighting, and multiple storage compartments for organized freezing.',
 'Convenient upright design with organized storage',
 749.99, 899.99, 8, 'GE-FRZ-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"capacity": "14 cu ft", "type": "upright", "frost_free": true, "adjustable_shelves": true}',
 '2 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'deep-freezers'),
 (SELECT id FROM brand_ids WHERE slug = 'electrolux'),
 now(), now()),

(uuid_generate_v4(), 'Whirlpool Chest Freezer 7.0 cu ft', 'whirlpool-chest-freezer-7',
 'Compact chest freezer perfect for small spaces',
 'Space-saving chest freezer',
 299.99, 379.99, 18, 'WHP-FRZ-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"capacity": "7.0 cu ft", "type": "chest", "energy_star": true}',
 '1 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'deep-freezers'),
 (SELECT id FROM brand_ids WHERE slug = 'whirlpool'),
 now(), now()),

(uuid_generate_v4(), 'LG Convertible Freezer 11.1 cu ft', 'lg-convertible-freezer-11-1',
 'Convertible freezer that can switch between freezer and refrigerator modes',
 'Flexible storage solution with dual modes',
 899.99, 1099.99, 6, 'LG-FRZ-001',
 ARRAY['/placeholder.svg?height=400&width=400'],
 '{"capacity": "11.1 cu ft", "type": "convertible", "dual_mode": true, "smart_features": true}',
 '3 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'deep-freezers'),
 (SELECT id FROM brand_ids WHERE slug = 'lg'),
 now(), now());
